name: FirstPLUGin
version: '${project.version}'
main: me.davvolol.firstplugin.FirstPLUGin
api-version: 1.19
depend: [WorldGuard]
commands:
  PMAC:
    description: Simple command to enable PMAC
    permission: pvpmania.pmac
    usage: /<command>
  Ffakit:
    description: Kit that opens an inventory with kits
    usage: /<command>
  Enchanter:
    description: Enchanter gui
    permission: pvpmania.enchanter
    usage: /<command> <player>
  Blacksmith:
    description: Blacksmith gui
    permission: pvpmania.blacksmith
    usage: /<command> <player>
  Bazaar:
    description: Bazaar gui
    permission: pvpmania.bazaar
    usage: /<command> <player>
  Stats:
    description: Stats gui
    usage: /<command> clear <player>
  Discord:
    description: Discord command
    usage: /<command>
